### PR TITLE
Upgrade to nan to 2.0.9

### LINKED ISSUE #67: Upgrade to nan 2.x
To support Node.js 4.x.

Also adding to nodejs/node#2798.

### PR DESCRIPTION
**Pull request by marcominetti**
@audreyt 

Almost done, it compiles and tests are passed on 0.10.40 and 0.12.7.

In node.js 4.1.0 compiles but segmentation fault occurs, your knowledge is required to close #67.

### CODE REVIEW

**Comment by marcominetti** [comment]
I've tested against iojs 3.3.1 and all tests pass. I suppose it could be something with the new v8 4.5.x.

**Comment by audreyt** [comment]
Thank you so much for the work! :rainbow:

**Comment by rainder** [comment]
does not work on node 4.1.0 though :cry:

**Comment by audreyt** [comment]
Released as 0.5.7 — supporting iojs 3.3.1 is better than not supporting it...

**Comment by brodybits** [comment]
I just issued PR #69 to fix the crash on Node 4.x.

**Pull request merged**
