### PR TITLE
Changes for review so far 2015.09.27

### PR DESCRIPTION
**Pull request by brodybits**
Here are my changes so far:
- Use npm bindings module and add index.js to make this project easier to test
- Completely remove the old pthread mechanism
- Use thread->isolate in node::FatalException() call to fix a deprecated function call warning
- Fixes to support Node 0.10/0.11/0.12 (*partially* broken by PR #69)
- Remove some old code that was commented out

If approved I would like to push them directly to the `master` branch later tonight.

### CODE REVIEW

**Comment by heavyk** [comment]
nice! really good

also, since you're in a cleaning mood, could you also make the file all spaces or tabs and perhaps an .editorconfig? that's been bothering me a while...

**Comment by audreyt** [comment]
LGTM! :+1:

**Comment by brodybits** [comment]
One more for review to mark 0.5.8-dev for next version, pushing the rest to your `master` branch

**Comment by brodybits** [comment]
All pushed to `master`, will work on the `.editconfig` (got me to try the Atom editor, like it so far, been using Vim which is pretty ancient!)

**Pull request merged**
